### ISSUE TITLE
`gulp` wont run after initial clone

### ISSUE THREAD

**Issue by barlock** [IBM-Watson/patterns#497]
After an initial clone and running `gulp` I'm presented with this stack trace

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'length' of undefined
    at Object.exports.fn (/Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/plugins/minifyStyles.js:47:24)
    at /Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:59:45
    at Array.filter (native)
    at monkeys (/Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at /Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:66:17
    at Array.filter (native)
    at monkeys (/Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at /Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:66:17
    at Array.filter (native)
    at monkeys (/Users/michael/workspace/design-guide/node_modules/runner/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/lib/svgo/plugins.js:46:39)
```

I think the problem has something to do with watson-runners imagemin task but I'm not sure exactly what is causing it.

**Comment by Snugug** [comment]
Did you follow our [Developing for the Design Guide](https://github.com/IBM-Watson/design-guide/wiki/Developing-for-the-Design-Guide) instructions and have the right version of Node?
